### ISSUE TITLE
App crashed only on iOS while joining a room

### ISSUE THREAD

**Issue by anagar23** [oney/react-native-webrtc#503] opened 2018-08-20 16:55 UTC
Exception '-[RTCPeerConnection setVideoTrackAdapters:]: unrecognized selector sent to instance 0x1601eb20' was thrown while invoking peerConnectionInit on target WebRTCModule with params (
        {
        iceServers =         (
                        {
                url = "stun:stun.l.google.com:19302";
            }
        );
    },
    0
)

callstack: (
	0   CoreFoundation                      0x1afebb55 <redacted> + 152
	1   libobjc.A.dylib                     0x1a273067 objc_exception_throw + 38
	2   CoreFoundation                      0x1aff0fd1 <redacted> + 0
	3   CoreFoundation                      0x1afef0c3 <redacted> + 696
	4   CoreFoundation                      0x1af17dc8 _CF_forwarding_prep_0 + 24
	5   elth                                0x001ac661 -[WebRTCModule(RTCPeerConnection) peerConnectionInit:objectID:] + 760
	6   CoreFoundation                      0x1aff0354 <redacted> + 68
	7   CoreFoundation                      0x1af142b9 <redacted> + 300
	8   CoreFoundation                      0x1af17e87 <redacted> + 48
	9   elth                                0x0027fe97 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 1806
	10  elth                                0x00303ea1 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 640
	11  elth                                0x00303a25 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 176
	12  elth                                0x00303971 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 16
	13  libdispatch.dylib                   0x017d8467 _dispatch_call_block_and_release + 10
	14  libdispatch.dylib                   0x017e466f _dispatch_queue_serial_drain + 988
	15  libdispatch.dylib                   0x017dba39 _dispatch_queue_invoke + 872
	16  libdispatch.dylib                   0x017e676b _dispatch_root_queue_drain + 666
	17  libdispatch.dylib                   0x017e6471 _dispatch_worker_thread3 + 112
	18  libsystem_pthread.dylib             0x1a86e87d _pthread_wqthread + 1040
	19  libsystem_pthread.dylib             0x1a86e45c start_wqthread + 8
)

#### Expected behavior

The app should not crash

#### Observerd behavior

App crash on exchange method, while RCTPeerConnection initialized. A native error caused.

#### Platform information

* **react-native: 0.51.1*:
* **"react-native-webrtc": "^1.67.0",**:
* **OS**: 
* **iPhone 5C**:

When I run the demo app, it works fine for the device. But if I integrate the same code base in my app it crashed while I join the same room from Heroku server.

**Comment by saghul** [comment] 2018-08-20 18:53
Duplicate of #502

**Closed by saghul** 2018-08-20 18:53 UTC
