### ISSUE TITLE
Very very slow on Android

### ISSUE THREAD

**Issue by tezqa** [oney/react-native-webrtc#146] opened 2016-10-11 12:04 UTC
This library runs on the main UI thread. If you have a lot of components to render, they will slow down WebRTC and WebRTC will slow down their render cycle.

I did this test:
With a very basic view with no more than 2 or 3 components to render, everything works very well.
But with a view + a navigator, list, tabs and more, WebRTC is very slow, i have to wait 1 minute or so to get 2 peers connected.

Does anyone has noticed that?

Do you plan to run WebRTC on a separate thread?

**Comment by zxcpoiu** [comment] 2016-10-16 11:03
@tezqa I don't have video use cases so I can't comment much.

Currently, this repo doesn't have any specific plans.
You can fire a PR to improve it or have a discussion with someone has the similar scenario

you may interested in #126

**Comment by tezqa** [comment] 2016-10-17 07:54
It has nothing to do with video and streaming.
I have only declared an PeerConnection with a simple DataChannel, nothing more.

**Comment by zxcpoiu** [comment] 2016-10-17 08:27
I'm not sure about which thread it's running but I always render webrtc in
another "modal view" and let my components only render if needed by
customise "shouldComponentUpdate"

I think if your observation is valid, then it's the only way to avoid
before moving webrtc runs on another thread.

Do you have any hints to do that about thread?

**Comment by tezqa** [comment] 2016-10-30 09:52
@zxcpoiu Do you log a lot of things with console.log or console.* statements?

I'm experiencing slow downs for others React Native projects (without WebRTC) and it appears that logging with console.log in development really slow downs apps, especially on iOS. And the thread responsible for that is the Javascript thread used by RN.

Here is another thread about this issue:
https://github.com/evgenyrodionov/redux-logger/issues/32

I will test by disabling any logs and post my result here asap. I know i have a lots of logs because i'm logging everything that happens with WebRTC (Ice Candidates, etc.)

**Comment by zxcpoiu** [comment] 2016-10-31 10:11
@tezqa 

yes, I have lots of log as well. ( roughly hundreds of line at the starting process of a call )
my personal experience is:

* both platform works fine in release mode
* on android debug build, it works fine if I disable `_DEV_` option
* on ios debug build, it's always slow like if android `_DEV_` is on.

not sure if it caused by logging, but to optimize components' life cycle is necessary along with your app become larger, especially complex navigation and whether should unmount components.

**Comment by saghul** [comment] 2017-06-16 04:36
No follow-up, closing. FWIW, we haven't seen this (the logging part yeah, but that's not an issue of this plugin) in Jitsi Meet, where we use this plugin.

**Closed by saghul** 2017-06-16 04:36 UTC

**Comment by tobiasmuecksch** [comment] 2017-07-24 08:59
@saghul I've testet the Jitsi Meet App on my android device and the video transmission is slow as hell.

Call Partner 1:  Motorola Moto G, 4th gen, Android 6.0
Call Partner 2: Chrome 59, Mac OS 10.12.5

**Comment by muhammadwafa** [comment] 2020-02-29 18:43
2020 same problem, the video motion is very slow, Also the quality is very low

**Comment by saghul** [comment] 2020-03-01 02:11
There are many things at play, but we’ve been using it in production with good results for years. That said there are probably things that can be improved, feel free to open a new issue if you discover anything.

**Comment by kiranNegiloni** [comment] 2023-07-03 15:07
Hi Team, i am using RTCview for streaming the screenshare. I am experiencing delay in rendering the screenshare video. Is there anything i can do to improve this?

**Comment by saghul** [comment] 2023-07-03 17:27
The original issue was posted many years ago, before we even had screen sharing. Please open a new one and post as many details as possible about your setup and what you experience.
