### ISSUE TITLE
EXC_BAD_ACCESS cricket::ChannelManager::GetSupportedFormats_

### ISSUE THREAD

**Issue by dguillamot** [oney/react-native-webrtc#92] opened 2016-06-16 18:59 UTC
We seem to be getting the following error. Not 100% of the time, but maybe 5-10% ? Have you seen this? Is it in the internal webrtc libraries? Should they be upgraded in react-native-webrtc? Any other thoughts? Thanks!

EXC_BAD_ACCESS·Attempted to dereference garbage pointer 0x180.
Full TraceRaw
immerse:0cricket::ChannelManager::GetSupportedFormats_w(cricket::VideoCapturer_, std::__1::vector<cricket::VideoFormat, std::__1::allocator<cricket::VideoFormat> >_) const 
 immerse:0rtc::Thread::ReceiveSendsFromThread(rtc::Thread const_)  
 immerse:0rtc::MessageQueue::Get(rtc::Message_, int, bool)  
 immerse:0rtc::Thread::ProcessMessages(int) 
 immerse:0rtc::Thread::PreRun(void*)  
 /usr/lib/system/libsystem_pthread.dylib:0_pthread_body 
/usr/lib/system/libsystem_pthread.dylib:0_pthread_start

**Comment by dguillamot** [comment] 2016-06-20 19:17
We are not using Firebase, but I did come across similar behavior mentioned here: https://bugs.chromium.org/p/webrtc/issues/detail?id=3992


Oney, is it possible that a similar libstdc++ issue is coming up when building the webrtc libs for react-native-webrtc

**Comment by zxcpoiu** [comment] 2016-06-21 05:51
@dguillamot 

the issue you post turned out to be a problem on firebase itself, would nothing to do with WebRTC. That issue got a `WontFix` tag.

I'm not familiar with it, guess that EXC_BAD_ACCESS means someone is trying to access memory blocks which doesn't belonged to him or the pointer has already dereferenced.

Since react app would mount and unmount components, maybe **one of** the directions to observe is to exam the flow between mount/unmount of the components and start/stop of the WebRTC resources, especially on `RTCView`, ex: WebRTC does not close cleanly before component unmount.

**two of** the directions is to upgrade WebRTC library to as latest stable as possible which I mentioned in #79

**Comment by oney** [comment] 2016-07-07 07:36
`EXC_BAD_ACCESS` means the object's memory is released and the memory is assigned to other object. It can be debugged by `NSZombies`. Please give more detail about reproducing.

**Comment by saghul** [comment] 2017-06-14 20:05
No follow-up, and we have since updated the library a number of times. Holler if you get a new crash!

**Closed by saghul** 2017-06-14 20:05 UTC
Labels: waiting author response
