### ISSUE TITLE
Block RTCView from rotating(orientation)

### ISSUE THREAD

**Issue by JoostVermeulen11** [oney/react-native-webrtc#336] opened 2017-08-24 13:55 UTC
Every time when I'm rotating my device, the RTCView is rotating with the devices orientation. In my next step I locked the orientation's device with the react-native-orientation plugin, but the only thing rotating is the RTCView, does anyone know how to solve this?

**Comment by saghul** [comment] 2017-08-24 16:07
Duplicate of #220.

**Closed by saghul** 2017-08-24 16:07 UTC
