### ISSUE TITLE
Sometimes showing black screen in remoteview

### ISSUE THREAD

**Issue by swaroopa94** [oney/react-native-webrtc#251] opened 2017-04-10 04:44 UTC
Hi,

I am using your module for video calling.
My issue is 
I am not able to see the remote view sometimes when entering into the room, but sometimes it works fine.
this occurs mainly in Android devices some times it crashes also.

Can you tell me why I am getting a black screen in place of remote view.

Thanks in advance.

**Comment by wumke** [comment] 2017-06-02 12:20
I also see black remote views sometimes (at both sides!)... mostly when android device created the offer and ios device the answer. No clue yet why, but if I find the reason I'll share it here!

**Comment by saghul** [comment] 2017-06-02 14:00
FWIW, we have also seen this occasionally, though we haven't been able to find the cause.

**Comment by saghul** [comment] 2017-09-06 08:56
We have applied several fixes over time so I'm going to tentatively close this. Please holler if it needs reopening.

**Closed by saghul** 2017-09-06 08:56 UTC

**Comment by CandyOgre** [comment] 2017-09-26 14:52
@saghul how you fixed this bug? I faced with bug. I can see my peer, but if I run that builded apk file later, I can see him and he can't see me too

**Comment by farman-Ameer** [comment] 2018-11-06 06:06
I am facing same issue on ios. Remot video shows only for 1 sec then it goes black screen.
