### ISSUE TITLE
Can we add ontrack event instead of onaddstream

### ISSUE THREAD

**Issue by arindam89** [oney/react-native-webrtc#491] opened 2018-07-28 18:51 UTC
On add stream is getting deprecated.

**Comment by arindam89** [comment] 2018-07-28 18:51
Not sure if there is any difference.

**Comment by arindam89** [comment] 2018-07-28 18:54
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/onaddstream

**Comment by saghul** [comment] 2018-08-15 14:26
Duplicate of #433

**Closed by saghul** 2018-08-15 14:26 UTC
