### ISSUE TITLE
Multiple peers don't work

### ISSUE THREAD

**Issue by tezqa** [oney/react-native-webrtc#144] opened 2016-10-06 17:26 UTC
Everything works fine with only 2 peers. Each peer creates its RTCPeerConnection and can communicate with messages, using RTCDataChannel.

But when a third peer comes (peer 3), he creates two RTCPeerConnection to communicate with peers 1 & 2 and these peers create a new RTCPeerConnection to connect to this new peer and:
- all messages sent by the peers 1 & 2 with all theirs RTCDataChannel are received by peer 3 and not between them.
- all messages sent by peer 3 with all its RTCDataChannel are received by only peer 1 or 2, but not both.

I'm not sure if this issue is only related to RTCDataChannel. Maybe it's related to RTCPeerConnection and it affects audio and video streaming too.

Any idea?

Here is my code:
https://codeshare.io/O349o

**Comment by tezqa** [comment] 2016-10-07 11:14
I found what's going on.

In RTCPeerConnection.js
`} else {
      // Allocate a new id.
      // TODO Remembering the last used/allocated id and then incrementing it to
      // generate the next id to use will surely be faster. However, I want to
      // reuse ids (in the future) as the RTCDataChannel.id space is limited to
      // unsigned short by the standard:
      // https://www.w3.org/TR/webrtc/#dom-datachannel-id. Additionally, 65535
      // is reserved due to SCTP INIT and INIT-ACK chunks only allowing a
      // maximum of 65535 streams to be negotiated (as defined by the WebRTC
      // Data Channel Establishment Protocol).
      for (id = 0; id < 65535 && dataChannelIds.has(id); ++id);
      // TODO Throw an error if no unused id is available.
      dataChannelDict = Object.assign({id}, dataChannelDict);
    }`

The id assigned to a new channel is always equal to 0, resulting in conflicts between all dataChannels.

The workaround is to set your own id to your dataChannels:
`const myDataChannelOptions = {
    id: getRandomInt(1, 1000),
    ordered: true,
    reliable: true,
    negotiated: false // must be false to share this channel and its id with the other peer (false by default)
  };

 const myDataChannel = pc.createDataChannel('mainDataChannel', myDataChannelOptions);

...

function getRandomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1) + min);
}`

I have not found a way yet to generate an unique id, since this id has to be unique between all created dataChannels, but it works.

Another issue found: if I increase the maximum value possible for the random id, the app crashes . I have only tested on Android for the moment. I will post later the Logcat crash report .

**Comment by tezqa** [comment] 2016-10-07 11:46
Here is the logcat crash report:

```
E/rtc: #
                                                               # Fatal error in ../../webrtc/api/java/jni/peerconnection_jni.cc, line 1682
                                                               # last system error: 88
                                                               # Check failed: nativeChannelPtr
                                                               # Failed to create DataChannel
                                                               #
```

**Comment by lyubomir** [comment] 2016-10-25 19:41
As you've pointed out (the greatest part of) the problem is the RTCDataChannel's id. Unfortunately, the option to always generate your own ids doesn't solve the whole problem because you cannot generate your own id for an RTCDataChannel that is opened remotely.

The problem in react-native-webrtc's implementation is related to the fact that RTCDataChannel's id must be unique but only within its associated PeerConnection. However, the bridging from Objective-C to JavaScript identifies RTCDataChannels by their ids alone without taking into account the associated PeerConnection. Consequently, RTCDataChannel ids get into conflict across multiple PeerConnections. The solution I'm thinking of is using both the RTCDataChannel id and the associated PeerConnection when bridging from Objective-C to JavaScript in order to preserve the uniqueness.

**Comment by lyubomir** [comment] 2016-10-28 17:05
I believe I have an work-in-progress version of a fix for this in the master of jitsi/react-native-webrtc: https://github.com/jitsi/react-native-webrtc/commit/77e5a8d5884984df3725ee047cab1b5ed214b8d4. I'm still testing it and I may amend the commit in question so that's why I haven't committed it here yet.

**Comment by lyubomir** [comment] 2016-10-29 18:33
@tezqa, could you please test with https://github.com/oney/react-native-webrtc/commit/77e5a8d5884984df3725ee047cab1b5ed214b8d4 which works for me on both Android and iOS as far as RTCDataChannels are concerned.

https://github.com/oney/react-native-webrtc/commit/793143ba68e720388d4d5e69011fc472d32f87ca should fix a similar issue on Android related to MediaStream. I haven't got a fix for iOS yet because WebRTC.framework creates multiple Objective-C instances for one and the same underlying webrtc::MediaStreamInterface... but eventually we'll have to think of something.

**Comment by tezqa** [comment] 2016-10-30 09:42
@lyubomir I will test it asap, but for the moment i'm using socket.io as an alternative to webrtc. But i'm sad because i love WebRTC and i hope its implementation in React Native will be more mature in a near future. Obviously, I will help you guys to achieve this :)

**Closed** 2017-06-16 04:34 UTC
