### ISSUE TITLE
getUserMedia crash on latest RN version

### ISSUE THREAD

**Issue by pewh** [oney/react-native-webrtc#400] opened 2018-01-04 13:31 UTC
#### Expected behavior
Installed RN 0.51, and access getUserMedia will not make app crash

#### Observerd behavior
Crash unless I commenting `getUserMedia` section

#### Steps to reproduce the problem
Clone example repo at https://github.com/oney/RCTWebRTCDemo, that using RN 0.4x and it's work. But if I upgrade RN to 0.5x, it crash. But if I comment `getUserMedia`, the app will not crash.

#### Platform information

* **React Native version**: 0.51
* **Plugin version**: 1.58.3 & master
* **OS**:  Android
* **OS version**: Jelly Bean

**Comment by zxcpoiu** [comment] 2018-01-08 06:06
Do you know what kind / which part causes crash?
It probably caused by breaking changes in the newer RN version.

**Comment by Dimous** [comment] 2018-01-08 11:43
I use RN 0.52.0-rc.0 and it crashed till I set minWidth/minHeight constraints to 200x200

**Comment by saghul** [comment] 2018-01-08 13:05
I just tested 0.51.0 and works no problem here. Please specify *what* crashes and show us a backtrace. Closing until then.

**Closed by saghul** 2018-01-08 13:05 UTC

**Comment by hexiao-o** [comment] 2018-05-30 11:44
Has the problem been fixed?
