### ISSUE TITLE
Non-public api usage publish app ios

### ISSUE THREAD

**Issue by Terminus80** [oney/react-native-webrtc#615] opened 2019-04-03 14:40 UTC
Hi, 
I received a Non-public API usage  issue  during publish my App.

Below the methods: 
addStream:, channelId, initWithURLStrings:, isBinary, sdp, sendData:, setChannelId:, setIsEnabled:, stringForType.

#### Platform information

* **React Native version**: 0.58.5
* **Plugin version**:
1.63.0 M63
* **OS**: 
iOS
* **OS version**:
12.1

**Comment by saghul** [comment] 2019-04-03 14:44
Duplicate of https://github.com/oney/react-native-webrtc/issues/533

None of those are private APIs, we have been releasing to the Apple Store without issues for over 2 years now without a hitch. Alas, there is nothing we can do (that I know of) to solve this in our end,

**Closed by saghul** 2019-04-03 14:44 UTC

**Comment by boygiandi** [comment] 2019-10-03 03:41
The same problem here, @saghul can you try upload new app using this library ?
Email from apple : https://imgur.com/a/yhcgXW4

**Comment by saghul** [comment] 2019-10-03 05:08
I uploaded an app (Jitsi Meet) with this plugin just yesterday with no issues.

**Comment by boygiandi** [comment] 2019-10-12 00:52
Hi @saghul, this is the last email from apple

"Hello Nghiem,

I'm a senior Advisor with Apple Developer Program Support. Thank you for your patience while my internal teams reviewed your case.

They recommended you remove the following non-public selectors from their app and resubmit: 

initWithURLStrings:
setIsEnabled:
sendData:
typeForString:

If this does not correct the issue, please reply to my email so that we may continue troubleshooting.

Best regards,"

Can you do me a favor that rename these functions name, please ?
I tried my self but it look like impossible to me

Thank you so much

**Comment by saghul** [comment] 2019-10-12 04:06
You can’t, they are part of the WebRTC framework. They are wrong, you’ll have to insist those are not private APIs as they come from your own application.

**Comment by boygiandi** [comment] 2019-10-25 01:16
Hi @saghul , could you tell me how to build your WebRTC.framework ? I'll change function name and build it.
I tried this https://webrtc.org/native-code/ios/ but the framework at the end missing some files like : WebRTC/RTCVideoCodecFactory.h

**Comment by saghul** [comment] 2019-10-25 08:17
We use this script: https://github.com/react-native-webrtc/react-native-webrtc/blob/master/tools/build-webrtc.py

**Comment by ami9000** [comment] 2020-04-11 00:14
@boygiandi or @Terminus80 Were you able to solve this? According to this article, looks like Apple might be cracking down on private APIs more broadly: https://onezero.medium.com/apple-is-trying-to-kill-web-technology-a274237c174d

**Comment by boygiandi** [comment] 2020-04-11 00:51
I fixed it by upgrade react native webrtc package. Please try

**Comment by ami9000** [comment] 2020-04-11 01:18
> I fixed it by upgrade react native webrtc package. Please try

Awesome! Which version specifically worked for you?

**Comment by ami9000** [comment] 2020-04-11 01:19
> I fixed it by upgrade react native webrtc package. Please try

@boygiandi Awesome! Which version specifically worked for you?

**Comment by boygiandi** [comment] 2020-04-11 01:34
Just use latest version
